version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: pets-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: node:22-alpine
    container_name: express-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/coder
      - JWT_SECRET=Ddfajdis
    depends_on:
      - mongo
  
volumes:
  mongo-data: